### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by BaseMale** [b3nj5m1n/lemonblocks#6]
There is a small memory leak that accumulates over time.  I'm fairly certain the code in updateStatus that writes to blockToUpdate->status is part of the problem.  I don't see the old value being free'd anywhere.  Perhaps instead of dynamically allocating memory, moving to statically allocated arrays would be a safer and more optimal pattern to adopt?

**Comment by b3nj5m1n** [comment]
Hi, thanks for raising an issue.
I have been aware of this for a while, although I wasn't able to pinpoint what exactly was the cause of this problem (Granted, I haven't done extensive debugging).
You're probably right about statically allocated arrays being safer, however I'm not sure if I will try to implement it, as I am considering alternative bar feeders myself. I'm currently working on porting my config to [luastatus](https://github.com/shdown/luastatus) whichs philosophy seems pretty appealing. It's also a lot more mature and popular, and therefore more stable.
I'll consider implementing this, in the meantime, I suggest you look for an alternative too, sorry for the inconvenience. (Or implement it yourself, I'm always open to pull requests)
