### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by BeyondMagic** [b3nj5m1n/lemonblocks#8]
**wm**: dwm
**term**: st

```bash
~ Σ lemonblocks
[1]    234088 segmentation fault (core dumped)  lemonblocks
~ Σ
```

```bash
~ Σ start-lemonbar.sh
lemonblocks: no process found
mkfifo: fifo '/tmp/lemonblockspipe' を作成できません: ファイルが存在します
/usr/bin/start-lemonbar.sh: 40 行: 234624 Segmentation fault      (コアダンプ) lemonblocks
~ Σ
```

I put the fonts that I use normally and commented out `xdo`.

**Comment by b3nj5m1n** [comment]
Sorry but I can't seem to reproduce this, are you on the latest version?

**Comment by BeyondMagic** [comment]
Yep, I cloned the repository, if there is a aur version, I'll try it.

**Comment by b3nj5m1n** [comment]
There's no AUR version, could you please remove the directory, then clone it again, make and run the executable from the bin directory?

**Comment by BeyondMagic** [comment]
Okay!

**Comment by BeyondMagic** [comment]
![ss](https://user-images.githubusercontent.com/51831435/108866241-c5f9da80-75d2-11eb-826a-c4681a738678.png)

I did clone it again, it's not showing up there because I did clear the console, but I promise I did, :zany_face:

**Comment by b3nj5m1n** [comment]
I'm able to reproduce the issue, it's something with the config file, give me an hour or so.

**Comment by BeyondMagic** [comment]
Ok, thank you :)

**Comment by b3nj5m1n** [comment]
Nevermind, give me 2 minutes.

**Comment by b3nj5m1n** [comment]
Should be fixed with 64087f792504ad40d91ec6a35a02342e551b3086, please pull the update, then run `make config`, that should replace the default config (Which was outdated).

**Comment by BeyondMagic** [comment]
It's working, thanks!

**Comment by BeyondMagic** [comment]
Oh, just one last thing, @b3nj5m1n, is possible to have two bars?

**Comment by b3nj5m1n** [comment]
@BeyondMagic The fifo path is currently hard coded, so atm it's not possible, unless you want the two bars to have the exact same content.

I don't really actively work on this project anymore, so don't expect me to implement such a feature in the near future, I'm always open to PRs though.
